#version: '3'
#services:
#  web:
#    volumes:
#      - ./app:/app
#    ports:
#      - "80:80"
#    environment:
#      - FLASK_APP=main.py
#      - FLASK_DEBUG=1
#      - 'RUN=flask run --host=0.0.0.0 --port=80'
    # command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
version: '3.7'

services:

  mlapp:
    build:
      context: ./services/mlapp
      dockerfile: Dockerfile
    volumes:
      - './services/mlapp:/usr/src/app'
    ports:
      - 5001:5000
    tty: true # para que se mantenga sin necesidad de run un server
    container_name: mlapp_py
    environment:
      - FLASK_APP=project/app.py #project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig  # new
    #  # - 'RUN=flask run --host=0.0.0.0 --port=5000'